### ISSUE TITLE
Question about controller.py

### ISSUE THREAD

**Issue by AliBaheri** [r7vme/learning-to-drive-in-a-day#4]
Hi @r7vme,
I have a quick question about `controller.py`. Can you please say what is the goal of this script? I am a bit confuse about the overall approach. I understand that the Gym environment has been modified such that the input is the latent representation (coming from VAE) of each image (and not the raw image), but the rest of you approach is still unclear. Pluse, It seems you save the raw images in a buffer, but why, when you have a latent representation. Would you please clarify a bit?

**Comment by r7vme** [comment]
Hi @AliBaheri love that you're asking questions.

>  Can you please say what is the goal of this script? 

To buffer training data for VAE optimization in runtime.

> Pulse, It seems you save the raw images in a buffer, but why, when you have a latent representation. 

Because to train VAE you need raw images.

Let's say we started a script:
before episode 1: **VAE initialized with zeros, DDPG initialized with zeros.** (so both will output "trash")
episode 1: Run VAE+DDPG, DDPG collects images+state to it's buffer, VAE collects raw images to it's buffer
after episode 1: **Run VAE optimization**, Skip DDPG optimization for episodes 1-10 (staring from episode 11 we start optimize DDPG too)
...
repeat many times

After episode 1 we should have already little bit trained VAE and DDPG not just zeroes that output "trash". And after every episode both VAE and DDPG will improve.

**Comment by AliBaheri** [comment]
Got it. Thanks @r7vme for your clarification. 

Would it be possible to have your email for further communications.
Regards,

**Comment by r7vme** [comment]
@AliBaheri i like to do conversations in public issue, so other people can see and find their answers in the future. But we definitely can talk via email, i'm also open for a short talk as this field is really interesting to me and talking with researchers like you is really cool. email: rsokolkov@gmail.com
